version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: clicker-competition
      MYSQL_USER: root
      MYSQL_PASSWORD: pestillo
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
