openapi: "3.0.3"
info:
  title: "demo API"
  description: "demo API"
  version: "1.0.0"
servers:
  - url: "https://demo"
paths:
  /cities:
    get:
      summary: "GET cities"
      operationId: "allCitiesList"
      responses:
        200:
          description: "OK"
  /cities/clicks:
    get:
      summary: "GET cities/clicks"
      operationId: "allCityListOrder"
      responses:
        200:
          description: "OK"
  /city:
    post:
      summary: "POST city"
      operationId: "cityAddSimple"
      responses:
        200:
          description: "OK"
  /city/AutonomousCommunity/{id}:
    get:
      summary: "GET city/AutonomousCommunity/{id}"
      operationId: "getCityAutonomousCommunity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT city/AutonomousCommunity/{id}"
      operationId: "updateCityAc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE city/AutonomousCommunity/{id}"
      operationId: "deleteCityAc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /city/{id}:
    get:
      summary: "GET city/{id}"
      operationId: "getOnCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT city/{id}"
      operationId: "updateCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    post:
      summary: "POST city/{id}"
      operationId: "cityAddWithAc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE city/{id}"
      operationId: "deleteCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /communities:
    get:
      summary: "GET communities"
      operationId: "allCommunitieslist"
      responses:
        200:
          description: "OK"
  /communities/clicks:
    get:
      summary: "GET communities/clicks"
      operationId: "allCommunitiesListOrder"
      responses:
        200:
          description: "OK"
  /community:
    post:
      summary: "POST community"
      operationId: "communityAddSimple"
      responses:
        200:
          description: "OK"
  /community/country/{id}:
    get:
      summary: "GET community/country/{id}"
      operationId: "getAutonomousCommunityCountry"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT community/country/{id}"
      operationId: "updateCommunityCountry"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE community/country/{id}"
      operationId: "deleteCityAuc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /community/{id}:
    get:
      summary: "GET community/{id}"
      operationId: "getOneCommunity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT community/{id}"
      operationId: "updateCommunity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    post:
      summary: "POST community/{id}"
      operationId: "communityAddWithCountry"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE community/{id}"
      operationId: "deleteAutonomousCommunity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /country:
    post:
      summary: "POST country"
      operationId: "addSimpleCountry"
      responses:
        200:
          description: "OK"
  /login:
    post:
      summary: "POST login"
      operationId: "login"
      parameters:
        - name: "name"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "password"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "OK"
  /logout:
    get:
      summary: "GET logout"
      operationId: "logout"
      responses:
        200:
          description: "OK"
  /player:
    post:
      summary: "POST player"
      operationId: "playerAddSimple"
      responses:
        200:
          description: "OK"
  /player/avatar:
    post:
      summary: "POST player/avatar"
      operationId: "setPlayerAvatar"
      parameters:
        - name: "id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: "file"
          in: "query"
          required: true
      responses:
        200:
          description: "OK"
  /player/avatar/{id}:
    get:
      summary: "GET player/avatar/{id}"
      operationId: "getPlayerAvatar"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE player/avatar/{id}"
      operationId: "deletePlayerAvatar"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /player/city/{id}:
    get:
      summary: "GET player/city/{id}"
      operationId: "getPlayerCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT player/city/{id}"
      operationId: "updatePlayerCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    post:
      summary: "POST player/city/{id}"
      operationId: "playerAddWithCity"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /player/clicks/{id}:
    put:
      summary: "PUT player/clicks/{id}"
      operationId: "UpdateClicks"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /player/{id}:
    get:
      summary: "GET player/{id}"
      operationId: "getOnePlayer"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT player/{id}"
      operationId: "updatePlayer"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE player/{id}"
      operationId: "deletePlayer"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /players:
    get:
      summary: "GET players"
      operationId: "allPlayersList"
      responses:
        200:
          description: "OK"
  /players/clicks:
    get:
      summary: "GET players/clicks"
      operationId: "allPlayerListOrder"
      responses:
        200:
          description: "OK"
  /rol/{id}:
    get:
      summary: "GET rol/{id}"
      operationId: "roles"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /team:
    post:
      summary: "POST team"
      operationId: "teamAddSimple"
      responses:
        200:
          description: "OK"
  /team/avatar:
    post:
      summary: "POST team/avatar"
      operationId: "setTeamAvatar"
      parameters:
        - name: "id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: "file"
          in: "query"
          required: true
      responses:
        200:
          description: "OK"
  /team/avatar/{id}:
    get:
      summary: "GET team/avatar/{id}"
      operationId: "getTeamAvatar"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE team/avatar/{id}"
      operationId: "deleteTeamAvatar"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /team/player/{id}:
    post:
      summary: "POST team/player/{id}"
      operationId: "addPlayerToTeam"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE team/player/{id}"
      operationId: "deletePlayerFromTeam"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /team/players:
    get:
      summary: "GET team/players"
      operationId: "getAllTeamsWithPlayers"
      responses:
        200:
          description: "OK"
  /team/players/{id}:
    get:
      summary: "GET team/players/{id}"
      operationId: "getOneTeamWithPlayers"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /team/{id}:
    get:
      summary: "GET team/{id}"
      operationId: "getOneTeam"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT team/{id}"
      operationId: "updateTeam"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    delete:
      summary: "DELETE team/{id}"
      operationId: "deleteTeam"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
  /teams:
    get:
      summary: "GET teams"
      operationId: "allTeamsList"
      responses:
        200:
          description: "OK"
  /teams/clicks:
    get:
      summary: "GET teams/clicks"
      operationId: "allTeamsListOrder"
      responses:
        200:
          description: "OK"
  /countries:
    get:
      summary: "GET countries"
      operationId: "allCountryList"
      responses:
        200:
          description: "OK"
  /countries/clicks:
    get:
      summary: "GET countries/clicks"
      operationId: "allCountryListOrder"
      responses:
        200:
          description: "OK"
  /country/{id}:
    get:
      summary: "GET country/{id}"
      operationId: "getOneCountry"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"
    put:
      summary: "PUT country/{id}"
      operationId: "updateCountry"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        200:
          description: "OK"